spring:
  application:
    name: stock_service

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: xray-stock
      username: ${MONGO_USER}
      password: ${MONGO_PASS}

server:
  port: 8081

endpoint:
  stock-generator:
    base-url: http://localhost:8080/api/v1
