spring:
  application:
    name: stock_service

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: xray-stock
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true

endpoint:
  stock-generator:
    base-url: http://localhost:8080/api/v1

socketio:
  secret-key: ${SOCKETIO_SECRET_KEY:6c9d9411-9727-47c4-9d76-64dcfb761083}
